#!/bin/sh
# chkconfig: 2345 55 45 
# description: start or stop gunicorn
### BEGIN INIT INFO
# Provides:	gunicorn_myblog
# Required-Srart: #all
# Required-Stop:  #all
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: 	starts the gunicorn server for myblog
# Description:		starts gunicorn using start-stop-daemon
### END INIT INFO
# Gunicorn init.d script for /etc/init.d/

#WARNING: user $RUN_AS must have +w on /var/run/gunicorn
WORKPATH="/root/PycharmProjects/untitled/"
NAME="myblog"
DESC="myblog"
CONF_FILE=${WORKPATH}"/myblog_gun.conf"
PIDFILE=""

while read line
do
    var=`expr index "${line}" =`
    length=${#line}
    item_value=${line:$var:$length-1}
    item_name=${line:0:$var-1}
    if [ $item_name == "pidfile" ]
    then
        PIDFILE=${item_value}
        break
    fi
done < ${CONF_FILE}

test ${#PIDFILE} > 0 || exit 0

PIDFILE=${PIDFILE#"'"}
PIDFILE=${PIDFILE#"\""}
PIDFILE=${PIDFILE%"'"}
PIDFILE=${PIDFILE%"\""}

start () {
    v_b_exists=0
    if [ -f ${PIDFILE} ]
    then
        read pid < ${PIDFILE}
        v_b_exists=`ps --no-heading ${pid} | wc -l`
        if [ $v_b_exists == 0 ]
        then
            rm ${PIDFILE} -rf
        fi
    fi
    if [ $v_b_exists == 0 ]
    then
        cd ${WORKPATH}
        gunicorn --config ${CONF_FILE} myblog:app
        sleep 1
        read pid < ${PIDFILE}
        echo "${DESC}(${pid}) is runing..."
        return 1
    else
        read pid < ${PIDFILE}
        echo "${DESC}(${pid}) is already runing..."
        return 0
    fi
}
stop () {
    v_b_exists=1
    if [ -f ${PIDFILE} ]
    then
        read pid < ${PIDFILE}
        v_b_exists=`ps --no-heading ${pid} | wc -l`
        if [ $v_b_exists == 0 ]
        then
            rm ${PIDFILE} -rf
            echo "${DESC} is not runing"
            return 0
        else        
            echo "Stoping ${NAME}(${pid})..."     
            kill ${pid}
            return 1
        fi
    else
        echo "${DESC} is not runing"
        return 0
    fi
}

status(){
    if [ -f ${PIDFILE} ]
    then
        read pid < ${PIDFILE}
        v_b_exists=`ps --no-heading ${pid} | wc -l`
        if [ $v_b_exists > 0 ]
        then
            echo "${NAME}(${pid}) is already runing"
        else
            rm ${PIDFILE} -rf
            echo "${DESC} is not running"
        fi
    else
        echo "${DESC} is not running"
    fi
    return 1
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        echo "Restarting $DESC"
        stop
        sleep 1
        start
        ;;
  status)
        status
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|status}" >&2
        exit 1
        ;;
esac
exit 0

